export const LOAD_EMPLOYEE_DATA_INITIATION = 'LOAD_EMPLOYEE_DATA_INITIATION';
export const LOAD_EMPLOYEE_DATA_SUCCESS = 'LOAD_EMPLOYEE_DATA_SUCCESS';
export const LOAD_EMPLOYEE_DATA_FAILURE = 'LOAD_EMPLOYEE_DATA_FAILURE';
