export const LOAD_ISSUE_DATA_INITIATION = 'LOAD_ISSUE_DATA_INITIATION';
export const LOAD_ISSUE_DATA_SUCCESS = 'LOAD_ISSUE_DATA_SUCCESS';
export const LOAD_ISSUE_DATA_FAILURE = 'LOAD_ISSUE_DATA_FAILURE';
export const SET_SECONDARY_FILTER_STATUS = 'SET_SECONDARY_FILTER_STATUS';
export const SET_SECONDARY_FILTER_STATE = 'SET_SECONDARY_FILTER_STATE';
export const SET_SECONDARY_FILTER_ORDER = 'SET_SECONDARY_FILTER_ORDER';
