export const LOAD_ISSUE_DATA_INITIATION = 'LOAD_ISSUE_DATA_INITIATION';
export const LOAD_ISSUE_DATA_SUCCESS = 'LOAD_ISSUE_DATA_SUCCESS';
export const LOAD_ISSUE_DATA_FAILURE = 'LOAD_ISSUE_DATA_FAILURE';
