export const SET_SECONDARY_FILTER_STATUS = 'SET_SECONDARY_FILTER_STATUS';
export const SET_SECONDARY_FILTER_STATE = 'SET_SECONDARY_FILTER_STATE';
export const SET_SECONDARY_FILTER_ORDER = 'SET_SECONDARY_FILTER_ORDER';
export const INCREMENT_DATA_VIEW_PAGE = 'INCREMENT_DATA_VIEW_PAGE';
